name: Deploy to Surge.sh

on:
  push:
    branches: [ "main" ]  # Se activa al hacer push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Usa un servidor Ubuntu para el despliegue
    
    steps:
      # Paso 1: Descarga el código del repositorio
      - uses: actions/checkout@v4  # Versión actualizada del action checkout
      
      # Paso 2: Instala Surge globalmente
      - name: Install Surge CLI
        run: npm install --global surge
      
      # Paso 3: Despliegue en Surge.sh (versión corregida)
      - name: Deploy to Surge.sh
        run: |
          surge ./ \
            --domain ${{ secrets.SURGE_DOMAIN }} \
            --token ${{ secrets.SURGE_TOKEN }}
