name: Deploy to Surge.sh

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Surge
        run: npm install --global surge
        
      - name: Deploy to Surge
        env:
          SURGE_DOMAIN: ${{ secrets.SURGE_DOMAIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: surge ./ $SURGE_DOMAIN --token $SURGE_TOKEN
